version: 0.2
phases:
  build:
    commands:
      - echo "Build started"
artifacts:
  files:
    - '**/*'

batch:
  fast-fail: false
  build-list:
    - identifier: build1
      buildspec: buildspec-build1.yml
    - identifier: build2
      buildspec: buildspec-build2.yml
